export const tipsAndFacts = [
  "Women have been shown to contribute significantly to economic growth and development, but their full potential is often untapped.",
  "Gender equality is not just a women's issue; it is essential for achieving a more inclusive and sustainable world.",
  "Girls' education is a crucial factor in promoting gender equality and breaking the cycle of poverty.",
  "Women still face significant pay gaps in many industries and countries compared to their male counterparts.",
  "Gender equality is not about treating everyone the same but giving both genders equal opportunities and support.",
  "Promoting women's representation in leadership positions can lead to more balanced decision-making and improved outcomes.",
  "Gender stereotypes limit both men and women and should be challenged to create a more equal society.",
  "Men play a crucial role in advancing gender equality by actively supporting and advocating for women's rights.",
  "Addressing gender-based violence and harassment is a vital step towards achieving a more equal world.",
  "Investing in women's health and well-being benefits societies as a whole and leads to healthier communities.",
  "Educate yourself about social issues and historical injustices.",
  "Speak up against discrimination and injustice.",
  "Be an ally to marginalized communities.",
  "Advocate for inclusive policies and equal rights.",
  "Challenge stereotypes and biases.",
  "Support diverse representation in media and organizations.",
  "Promote diversity in education and acknowledge all cultures and histories.",
  "Encourage workplace diversity and inclusivity.",
  "Support equal access to healthcare for all.",
  "Get involved in volunteering and community engagement for positive change.",
  "Social equality is interconnected with multiple aspects of a person's identity (intersectionality).",
  "Gender pay gap persists in many countries, highlighting the need for gender equality initiatives.",
  "Racial and ethnic minorities face systemic barriers leading to disparities in opportunities and outcomes.",
  "Significant progress has been made in securing LGBTQ+ rights and protections.",
  "Legislation like the Americans with Disabilities Act (ADA) addresses the rights of people with disabilities.",
  "Historical inequalities can have a lasting impact on future generations.",
  "Poverty and social inequality are closely connected.",
  "Global efforts through organizations like the United Nations work toward promoting social equality.",
  "Unconscious biases can influence decisions and perpetuate inequality.",
  "Appreciating and respecting diverse cultures is crucial in fostering social equality.",
  "Did you know that promoting social equality not only fosters a fairer society but also boosts economic growth? According to the World Economic Forum, reducing gender and racial inequality in the workforce could add trillions of dollars to the global economy over the next decade. Embracing diversity and ensuring equal opportunities for all benefits everyone, creating a more prosperous and harmonious world.",
];
